<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="kali" failures="0" tests="4" name="com.crm.BatchAccounts.FindAndDeleteBatchAccountTest" time="1.990" errors="1" timestamp="2025-04-16T13:27:19 EEST" skipped="3">
  <testcase classname="com.crm.BatchAccounts.FindAndDeleteBatchAccountTest" name="signIn" time="0.000">
    <skipped/>
  </testcase> <!-- signIn -->
  <system-out/>
  <testcase classname="com.crm.BatchAccounts.FindAndDeleteBatchAccountTest" name="setUp" time="1.990">
    <error message="Fișierul nu a fost găsit: src/test/java/com/resources/configfiles/locators.properties" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Fișierul nu a fost găsit: src/test/java/com/resources/configfiles/locators.properties
at com.Base.BaseTest.loadProperties(BaseTest.java:56)
at com.Base.BaseTest.setUp(BaseTest.java:43)
at com.crm.BatchAccounts.FindAndDeleteBatchAccountTest.setUp(FindAndDeleteBatchAccountTest.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:781)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:574)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:219)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
    </error>
  </testcase> <!-- setUp -->
  <system-out/>
  <testcase classname="com.crm.BatchAccounts.FindAndDeleteBatchAccountTest" name="signIn" time="0.000">
    <skipped/>
  </testcase> <!-- signIn -->
  <system-out/>
  <testcase classname="com.crm.BatchAccounts.FindAndDeleteBatchAccountTest" name="signIn" time="0.000">
    <skipped/>
  </testcase> <!-- signIn -->
  <system-out/>
</testsuite> <!-- com.crm.BatchAccounts.FindAndDeleteBatchAccountTest -->
